"""
Core module for LatentMesh.

Provides LatentLLM (the HuggingFace Transformers-based generation engine) and AgentOutput
(the per-node result container). Integrates with GlobalPrefixCache for efficient KV-cache
reuse across agents in a LangGraph pipeline.
"""

import io
import logging
import torch
from dataclasses import dataclass, field
from typing import Any, List, Optional, Tuple
from transformers import AutoModelForCausalLM, AutoTokenizer, DynamicCache

logger = logging.getLogger(__name__)


@dataclass
class AgentOutput:
    """
    Result returned by a single agent (LangGraph node) after generation.

    Attributes:
        text: The decoded text produced by this agent.
        debug_text: Diagnostic strings (e.g. logprob metrics) for tooling.
        tokens: Number of new tokens generated by this agent.
        input_tokens_uncached: Tokens that had to be freshly encoded (cache miss portion).
        cached_tokens: Tokens whose KV state was loaded from GlobalPrefixCache.
        output_tokens: Tokens produced during generation (same as ``tokens``).
    """
    text: Optional[str] = None
    debug_text: Optional[List[str]] = None
    tokens: int = 0
    input_tokens_uncached: int = 0
    cached_tokens: int = 0
    output_tokens: int = 0

    def __post_init__(self) -> None:
        if self.debug_text is None:
            self.debug_text = []

    def __repr__(self) -> str:
        return (
            f"AgentOutput(tokens={self.tokens}, "
            f"cached={self.cached_tokens}, uncached={self.input_tokens_uncached})"
        )


def extract_kv(kv_cache: Any) -> list:
    """
    Normalises KV-cache objects from different HuggingFace return formats into
    a flat list of ``(key_tensor, value_tensor)`` tuples — one per transformer layer.

    Supported formats:
      - tuple / list of ``(k, v)`` pairs (legacy)
      - ``DynamicCache`` with ``.key_cache`` / ``.value_cache`` lists
      - Layer-based caches with ``.layers[i].keys`` / ``.values``
    """
    if kv_cache is None:
        return []
    if isinstance(kv_cache, (tuple, list)):
        return list(kv_cache)
    if hasattr(kv_cache, "key_cache") and hasattr(kv_cache, "value_cache"):
        return list(zip(kv_cache.key_cache, kv_cache.value_cache))
    if hasattr(kv_cache, "layers"):
        return [(layer.keys, layer.values) for layer in kv_cache.layers]
    return list(kv_cache)


class LatentLLM:
    """
    HuggingFace Transformers generation engine with GlobalPrefixCache integration.

    Wraps ``AutoModelForCausalLM`` and transparently manages KV-cache storage /
    retrieval so that downstream agents skip re-encoding text already processed
    by upstream agents.
    """

    def __init__(
        self,
        model_name: str,
        device: str = "cuda",
        dtype: str = "auto",
        global_cache: Optional[Any] = None,
        debug: bool = False,
    ) -> None:
        """
        Args:
            model_name: HuggingFace model identifier or local path.
            device: Target device (``"cuda"`` or ``"cpu"``).
            dtype: Torch dtype name (e.g. ``"float16"``, ``"bfloat16"``).
                   ``"auto"`` defaults to ``float16``.
            global_cache: A ``GlobalPrefixCache`` instance for cross-agent KV reuse.
            debug: When ``True``, emit detailed logging during generation.
        """
        self.device = device if torch.cuda.is_available() else "cpu"
        self.model_dtype = getattr(torch, dtype) if dtype != "auto" else torch.float16
        self.global_cache = global_cache
        self.debug = debug

        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=self.model_dtype,
            device_map="auto" if self.device == "cuda" else None,
        )
        self.model.eval()

        # Guarantee a chat template exists so apply_chat_template never fails.
        if self.tokenizer.chat_template is None:
            self.tokenizer.chat_template = (
                "{% for message in messages %}"
                "{{ '<|im_start|>' + message['role'] + '\\n' + message['content'] + '<|im_end|>' + '\\n' }}"
                "{% endfor %}"
                "{% if add_generation_prompt %}"
                "{{ '<|im_start|>assistant\\n' }}"
                "{% endif %}"
            )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _prepare_past_kv(self, kv_data: Any) -> Optional[DynamicCache]:
        """Deserialise raw KV data (bytes, str handle, or tensor tuples) into a ``DynamicCache``."""
        if isinstance(kv_data, str):
            if not self.global_cache:
                raise RuntimeError(
                    "KV handle received but no global_cache provided for deserialization"
                )
            loaded_bytes = self.global_cache.store.load(kv_data)
            if loaded_bytes is None:
                raise ConnectionError(f"KV cache miss for key: {kv_data}")
            buffer = io.BytesIO(loaded_bytes)
            kv_data = torch.load(buffer, weights_only=False, map_location=self.device)
        elif isinstance(kv_data, bytes):
            buffer = io.BytesIO(kv_data)
            kv_data = torch.load(buffer, weights_only=False, map_location=self.device)

        if kv_data is None:
            return None

        cache = DynamicCache(config=self.model.config)
        for i, (k, v) in enumerate(extract_kv(kv_data)):
            cache.update(
                k.to(self.device, self.model.dtype),
                v.to(self.device, self.model.dtype),
                i,
            )
        return cache

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @torch.no_grad()
    def generate(
        self,
        messages: list[dict],
        max_new_tokens: int = 128,
        temperature: float = 0.6,
        top_k: int = 30000,
        top_p: float = 0.95,
        output_scores: bool = False,
    ) -> AgentOutput:
        """
        Generate text from a message history, transparently leveraging GlobalPrefixCache.

        Args:
            messages: Chat-format message list (``[{"role": ..., "content": ...}]``).
            max_new_tokens: Maximum tokens to generate.
            temperature: Sampling temperature; 0 = greedy.
            top_k: Top-k filtering bound.
            top_p: Nucleus sampling threshold.
            output_scores: If ``True``, compute mean logprob and attach to ``debug_text``.

        Returns:
            AgentOutput with the generated text, token counts, and optional diagnostics.
        """
        # 1. Expand the full prompt via chat template
        full_text = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True,
        )
        full_input_ids = self.tokenizer(
            full_text, return_tensors="pt", add_special_tokens=False,
        ).input_ids.to(self.device)

        total_input_tokens = full_input_ids.shape[1]
        past_key_values = None
        matched_tokens = 0

        # 2. GlobalPrefixCache lookup — longest prefix match
        if self.global_cache:
            best_match_text, cached_bytes = self.global_cache.query(full_text)
            if best_match_text and cached_bytes:
                prefix_ids = self.tokenizer(
                    best_match_text, return_tensors="pt", add_special_tokens=False,
                ).input_ids
                matched_tokens = prefix_ids.shape[1]

                # Verify tokenization alignment
                if (
                    matched_tokens <= full_input_ids.shape[1]
                    and torch.equal(prefix_ids[0], full_input_ids[0, :matched_tokens])
                ):
                    past_key_values = self._prepare_past_kv(cached_bytes)
                    if self.debug:
                        logger.info(
                            f"[LatentLLM] Cache HIT — reusing {matched_tokens} tokens, "
                            f"encoding {total_input_tokens - matched_tokens} new tokens"
                        )
                else:
                    matched_tokens = 0
                    past_key_values = None
                    if self.debug:
                        logger.warning("[LatentLLM] Cache prefix found but tokenisation misaligned — full re-encode")

        # 3. Only encode the delta (tokens not covered by the cache)
        input_ids = full_input_ids[:, matched_tokens:]
        uncached_tokens = input_ids.shape[1]

        past_length = past_key_values.get_seq_length() if past_key_values else 0
        current_length = input_ids.shape[1]

        attention_mask = torch.ones((1, past_length + current_length), device=self.device)
        cache_position = torch.arange(
            past_length, past_length + current_length, device=self.device,
        )

        # 4. Generation
        outputs = self.model.generate(
            input_ids=input_ids,
            past_key_values=past_key_values,
            attention_mask=attention_mask,
            cache_position=cache_position,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_k=top_k,
            top_p=top_p,
            do_sample=(temperature > 0.0),
            pad_token_id=self.tokenizer.eos_token_id,
            return_dict_in_generate=True,
            output_scores=True,
        )

        # 5. Decode only the newly generated tokens
        generated_ids = outputs.sequences[0, input_ids.shape[1]:]
        generated_text = self.tokenizer.decode(generated_ids, skip_special_tokens=True)
        num_output_tokens = len(generated_ids)

        returned_kv = outputs.past_key_values

        # 6. Store the updated KV cache back into GlobalPrefixCache
        if self.global_cache and returned_kv is not None:
            buffer = io.BytesIO()
            legacy_kv = extract_kv(returned_kv)
            torch.save(legacy_kv, buffer)

            new_full_text = full_text + generated_text
            self.global_cache.insert(new_full_text, buffer.getvalue())

        # 7. Optional logprob computation (used by VotingPrimitive)
        debug_metrics: list[str] = []
        if output_scores and hasattr(outputs, "scores") and len(outputs.scores) > 0:
            scores = torch.stack(outputs.scores, dim=1)
            probs = torch.softmax(scores, dim=-1)
            gen_logprobs = torch.gather(
                probs, 2, generated_ids.unsqueeze(0).unsqueeze(-1),
            ).squeeze()
            mean_logprob = gen_logprobs.log().mean().item()
            debug_metrics.append(f"mean_logprob:{mean_logprob}")

        if self.debug:
            logger.info(
                f"[LatentLLM] Generated {num_output_tokens} tokens "
                f"(cached={matched_tokens}, uncached={uncached_tokens})"
            )

        return AgentOutput(
            text=generated_text,
            debug_text=debug_metrics,
            tokens=num_output_tokens,
            input_tokens_uncached=uncached_tokens,
            cached_tokens=matched_tokens,
            output_tokens=num_output_tokens,
        )
